version: '3'
services:
  #db:
    #image: mysql:8.0
    #environment:
      #MYSQL_ROOT_PASSWORD: password
      #MYSQL_USER: user
      #MYSQL_PASSWORD: password
      #MYSQL_DATABASE: atopic_share_development
    #command: --default-authentication-plugin=mysql_native_password
    #volumes:
     #- ./db/mysql-data:/var/lib/mysql
  web:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/atopic_share
    ports:
      - "3000:3000"
    #depends_on:
      #- db
  nginx:
    build:
      context: .
      dockerfile: ./container/nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - web