version: '3'
services:
  #db:
    #image: mysql:8.0
    #environment:
      #MYSQL_ROOT_PASSWORD: password
      #MYSQL_USER: user
      #MYSQL_PASSWORD: password
      #MYSQL_DATABASE: atopic_share_development
    #command: --default-authentication-plugin=mysql_native_password
    #volumes:
     #- ./db/mysql-data:/var/lib/mysql
  web:
    build: 
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/atopic_share
      - public-data:/atopic_share/public
      - tmp-data:/atopic_share/tmp
      - log-data:/atopic_share/log
    networks:
      - atopic_share-network
    #depends_on:
      #- db
  nginx:
    build:
      context: ./nginx
    volumes:
      - public-data:/atopic_share/public
      - tmp-data:/atopic_share/tmp
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      - atopic_share-network
volumes:
  public-data:

  tmp-data:
  log-data:
  
networks:
  atopic_share-network:
    external: true
